//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class actividad
    {
        public actividad()
        {
            this.fecha_inicio = System.DateTime.Now;
            this.fecha_vencimiento = System.DateTime.Now;


        }
        public int id { get; set; }

        [Display(Name = "Oportunidad")]
        [Required(ErrorMessage = "Debe seleccionar Oportunidad")]
        public int id_oportunidad { get; set; }

        [Display(Name = "Contacto")]
        [Required(ErrorMessage = "Debe seleccionar Contacto")]
        public int id_contacto { get; set; }

        [Display(Name = "Fecha de Inicio")]
        [Required(ErrorMessage = "Debe ingresar Fecha de Inicio")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime fecha_inicio { get; set; }

        [Display(Name = "Fecha de Vencimiento")]
        [Required(ErrorMessage = "Debe seleccionar Fecha de vencimiento")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime fecha_vencimiento { get; set; }


        [Display(Name = "Título")]
        [Required(ErrorMessage = "Debe ingresar Título")]
        public string titulo { get; set; }

        [Display(Name = "Descripción")]
        [Required(ErrorMessage = "Debe ingresar Descripción")]
        public string descripcion { get; set; }


        [Display(Name = "Creada por")]
        [Required(ErrorMessage = "Debe Ingresar por quién fue creada")]
        public string creada_por { get; set; }

        public virtual oportunidades oportunidades { get; set; }
        public virtual usuario usuario { get; set; }

        public List<empresa> empresaList;
        public List<oportunidades> oList;
        public List<usuario> usuarioList;

        [Display(Name = "Tipo")]
        public string tipo_actividad { get; set; }


        [Display(Name = "Estado")]
        public string estado { get; set; }

        //public virtual empresa empresa { get; set; }
        //public virtual contactos contactos { get; set; }
        //public virtual contactos contactos1 { get; set; }
        //public virtual oportunidades oportunidades { get; set; }

        public List<SelectListItem> ContactoList { get; internal set; }
        public List<SelectListItem> UsuarioList { get; internal set; }

        public List<SelectListItem> opList { get; internal set; }

        //Lista de estados
        public List<string> estadoL = new List<string> { "Activa", "Cancelada","Finalizada" };

        //lista del tipo de actividad
        public List<string> tipo_actividadL = new List<string> { "Tarea", "Llamada", "Mail","Reunión" };





    }
}