//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    using System.Web.Script.Serialization;

    public partial class contacto_empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contacto_empresa()
        {
            this.oportunidades = new HashSet<oportunidades>();
            this.fecha_inicio_rel = System.DateTime.Now;
        }

        public int id { get; set; }
        [Display(Name = "Empresa")]
        [Required(ErrorMessage = "Seleccione Empresa")]
        public int id_empresa { get; set; }
        [Display(Name = "Contacto")]
        [Required(ErrorMessage = "Seleccione Contacto")]
        public int id_contacto { get; set; }
        [Display(Name = "Fecha de Inicio")]
        [Required(ErrorMessage = "Debe seleccionar Fecha")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime fecha_inicio_rel { get; set; }
        [Display(Name = "Fecha de Término")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> fecha_termino_rel { get; set; }
        [Display(Name = "Cargo")]
        public string cargo { get; set; }
        [Display(Name = "Teléfono Fijo")]
        [Required(ErrorMessage = "Seleccione Teléfono Fijo")]
        [DataType(DataType.Text)]
        public int telefono_fijo { get; set; }
        [Display(Name = "Teléfono Celular")]
        [Required(ErrorMessage = "Seleccione Teléfono Celular")]
        [DataType(DataType.Text)]
        public int telefono_celular { get; set; }

        public List<empresa> empresaListI;
        public List<contactos> contactoListI;


        [ScriptIgnore]
        public virtual empresa empresa { get; set; }
        public virtual contactos contactos { get; set; }

        public List<SelectListItem> empresaListSI { get; internal set; }
        public List<SelectListItem> contactosListSI { get; internal set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oportunidades> oportunidades { get; set; }

        public string FullName
        {
            get
            {
                return contactos.nombres + " " + contactos.apellidos;
            }
        }
        public string EmpresaName
        {
            get
            {
                return empresa.razon_social;
            }
        }



    }
}