//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class proyectob_dbEntities : DbContext
    {
        public proyectob_dbEntities()
            : base("name=proyectob_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public virtual DbSet<actividad> actividad { get; set; }
        public virtual DbSet<contacto_empresa> contacto_empresa { get; set; }
        public virtual DbSet<contactos> contactos { get; set; }
        public virtual DbSet<empresa> empresa { get; set; }
        public virtual DbSet<oportunidades> oportunidades { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<usuario_rol> usuario_rol { get; set; }
    }
}
