//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    using System.Web.Script.Serialization;

    public partial class empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empresa()
        {
            this.contacto_empresa = new HashSet<contacto_empresa>();
        }



        public int id { get; set; }
        [Required(ErrorMessage = "Debe ingresar Rut")]
        [Display(Name = "Rut")]
        public string rut { get; set; }
        [Display(Name = "Razón Social")]
        [Required(ErrorMessage = "Debe ingresar Razón Social")]
        public string razon_social { get; set; }
        [Display(Name = "Rubro")]
        [Required(ErrorMessage = "Debe ingresar Rubro")]
        public string rubro { get; set; }
        [Required(ErrorMessage = "Debe ingresar Calle")]
        [Display(Name = "Calle")]
        public string calle { get; set; }
        [Required(ErrorMessage = "Debe ingresar Número")]
        [DataType(DataType.Text)]
        [Display(Name = "Número")]
        public int numero { get; set; }
        [Display(Name = "Resto de Dirección")]
        [Required(ErrorMessage = "Debe ingresar Resto de dirección")]
        public string resto_direccion { get; set; }
        [Display(Name = "Comuna")]
        [Required(ErrorMessage = "Debe ingresar Comuna")]
        public string comuna { get; set; }
        [Display(Name = "CTG Empleados")]
        public string ctg_empleados { get; set; }
        [Display(Name = "Convenio")]
        [Required(ErrorMessage = "Debe ingresar Convenio")]
        public string convenio { get; set; }
        [Display(Name = "Zona")]
        [Required(ErrorMessage = "Debe ingresar Zona")]
        public string zona { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [ScriptIgnore]
        public virtual ICollection<contacto_empresa> contacto_empresa { get; set; }

        //Listas de los detalles
        public List<oportunidades> Opos { get; set; }
        [ScriptIgnore]
        public List<contacto_empresa> contactosM { get; set; }
        public List<actividad> Activs { get; set; }

        //para no usar viewbag en json
        [ScriptIgnore]
        public virtual List<contactos> listaContactos { get; set; }

        //Numero de oportunidades
        public int OposN;

        //Lista de convenio
        public List<string> convenioL = new List<string> { "Sí", "No" };

        public string DireccionCompleta
        {
            get { 
            return calle + " " + numero + " " + resto_direccion;

            }
        }
    }
}