//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class usuario_rol
    {
        public int id { get; set; }
        [Display(Name = "Usuario")]
        [Required(ErrorMessage = "Debe seleccionar Usuario")]
        public int id_usuario { get; set; }
        [Display(Name = "Rol")]
        [Required(ErrorMessage = "Debe ingresar Rol")]
        public int id_rol { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Fecha de creación")]
        [Required(ErrorMessage = "Debe seleccionar Fecha de Inicio de Relación")]
        public System.DateTime fecha_inicio_rel { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Fecha de Termino")]
        public Nullable<System.DateTime> fecha_termino_rel { get; set; }

        public virtual roles roles { get; set; }
        public virtual usuario usuario { get; set; }

        public virtual IEnumerable<roles> rolesList { get; set; }
        public virtual IEnumerable<usuario> usuarioList { get; set; }

        public List<SelectListItem> usuarioListI { get; internal set; }
        public List<SelectListItem> rolesListI { get; internal set; }




        public usuario_rol()
        {
            this.fecha_inicio_rel = System.DateTime.Now;
        }




        /*
      public bool esUser(string id_u, DateTime fechaCorte)
      {

          if (id_u == id && fechaCorte > fecha_termino_rel)
          {
              return true;
          }
          else
          {
              return false;
          }
      }


      public bool esAdmin(string id_u, DateTime fechaCorte)
      {

          if (id_u == id && fechaCorte > fecha_termino_rel && id_rol == "admin")
          {
              return true;
          }
          else
          {
              return false;
          }
      }

*/
    }
}
