//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.actividad = new HashSet<actividad>();
            this.oportunidades = new HashSet<oportunidades>();
            this.usuario_rol = new HashSet<usuario_rol>();
            this.fecha_inicio_rel = System.DateTime.Now;
            this.estado = estado;
        }

        public int id { get; set; }
        [Required(ErrorMessage = "Debe seleccionar Contacto")]
        [Display(Name = "Contacto")]
        public int id_contacto { get; set; }
        [Display(Name = "Estado")]
        private string _estado { get; set; }
        public string estado
        {
            get {
                if (fecha_termino_rel != null && fecha_termino_rel <= System.DateTime.Now)
                {
                    return "inactivo";
                }
                else
                {
                    return  "activo";
                }
            }
            set
            {
                if (fecha_termino_rel != null && fecha_termino_rel<= System.DateTime.Now)
                {
                    _estado = "inactivo";
                }
                else
                {
                    _estado = "activo";
                }
            }

        }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Fecha de Creación")]
        [Required(ErrorMessage = "Debe seleccionar Fecha de Inicio de Relación")]
        public System.DateTime fecha_inicio_rel { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Fecha de Término")]
        public Nullable<System.DateTime> fecha_termino_rel { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<actividad> actividad { get; set; }
        public virtual contactos contactos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oportunidades> oportunidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuario_rol> usuario_rol { get; set; }
        public virtual List<roles> rolesList { get; set; }
        public string LoginError { get; set; }

        public List<contactos> contactoList;
        public List<SelectListItem> contactoListI { get; set; }

        //Lista de detalles
        public List<usuario_rol> uRolesM { get; set; }
        public List<oportunidades> Ops { get; set; }
        public List<actividad> Activs { get; set; }


        public string FullName
        {
            get
            {
                return contactos.nombres + " " + contactos.apellidos;
            }
        }



    }
}